// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('CreateProject', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('CreateProject', async function() {
    // Test name: CreateProject
    // Step # | name | target | value
    // 1 | open | /projectList | 
    await driver.get("http://localhost:3001/projectList")
    // 2 | setWindowSize | 995x695 | 
    await driver.manage().window().setRect(995, 695)
    // 3 | click | css=.btn-sm | 
    await driver.findElement(By.css(".btn-sm")).click()
    // 4 | click | id=projectName | 
    await driver.findElement(By.id("projectName")).click()
    // 5 | type | id=projectName | test creation
    await driver.findElement(By.id("projectName")).sendKeys("test creation")
    // 6 | click | id=projectDesc | 
    await driver.findElement(By.id("projectDesc")).click()
    // 7 | type | id=sprintDelay | 3
    await driver.findElement(By.id("sprintDelay")).sendKeys("3")
    // 8 | click | id=sprintDelay | 
    await driver.findElement(By.id("sprintDelay")).click()
    // 9 | type | id=sprintDelay | 4
    await driver.findElement(By.id("sprintDelay")).sendKeys("4")
    // 10 | click | id=sprintDelay | 
    await driver.findElement(By.id("sprintDelay")).click()
    // 11 | doubleClick | id=sprintDelay | 
    {
      const element = await driver.findElement(By.id("sprintDelay"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 12 | type | id=projectDesc | test creation de projet
    await driver.findElement(By.id("projectDesc")).sendKeys("test creation de projet")
    // 13 | click | id=dateEnd | 
    await driver.findElement(By.id("dateEnd")).click()
    // 14 | type | id=dateEnd | 2020-11-21
    await driver.findElement(By.id("dateEnd")).sendKeys("2020-11-21")
    // 15 | click | css=.btn-success | 
    await driver.findElement(By.css(".btn-success")).click()
  })
})
