// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('CreateUS', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('CreateUS', async function() {
    // Test name: CreateUS
    // Step # | name | target | value
    // 1 | open | /projectList | 
    await driver.get("http://localhost:3001/projectList")
    // 2 | setWindowSize | 995x695 | 
    await driver.manage().window().setRect(995, 695)
    // 3 | click | css=.clickable-row:nth-child(3) > td:nth-child(1) | 
    await driver.findElement(By.css(".clickable-row:nth-child(3) > td:nth-child(1)")).click()
    // 4 | click | css=.nav-item:nth-child(7) span | 
    await driver.findElement(By.css(".nav-item:nth-child(7) span")).click()
    // 5 | click | css=.btn-sm | 
    await driver.findElement(By.css(".btn-sm")).click()
    // 6 | mouseOver | css=.btn-sm | 
    {
      const element = await driver.findElement(By.css(".btn-sm"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 7 | mouseOut | css=.btn-sm | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 8 | click | id=entantque | 
    await driver.findElement(By.id("entantque")).click()
    // 9 | select | id=entantque | label=Développeur
    {
      const dropdown = await driver.findElement(By.id("entantque"))
      await dropdown.findElement(By.xpath("//option[. = 'Développeur']")).click()
    }
    // 10 | click | css=#entantque > option:nth-child(2) | 
    await driver.findElement(By.css("#entantque > option:nth-child(2)")).click()
    // 11 | click | id=jesouhaite | 
    await driver.findElement(By.id("jesouhaite")).click()
    // 12 | type | id=jesouhaite | je crée une user story
    await driver.findElement(By.id("jesouhaite")).sendKeys("je crée une user story")
    // 13 | click | id=afinde | 
    await driver.findElement(By.id("afinde")).click()
    // 14 | type | id=afinde | pour tester
    await driver.findElement(By.id("afinde")).sendKeys("pour tester")
    // 15 | click | id=importance | 
    await driver.findElement(By.id("importance")).click()
    // 16 | select | id=importance | label=Moyenne-Basse
    {
      const dropdown = await driver.findElement(By.id("importance"))
      await dropdown.findElement(By.xpath("//option[. = 'Moyenne-Basse']")).click()
    }
    // 17 | click | css=#importance > option:nth-child(3) | 
    await driver.findElement(By.css("#importance > option:nth-child(3)")).click()
    // 18 | click | id=difficulte | 
    await driver.findElement(By.id("difficulte")).click()
    // 19 | select | id=difficulte | label=5
    {
      const dropdown = await driver.findElement(By.id("difficulte"))
      await dropdown.findElement(By.xpath("//option[. = '5']")).click()
    }
    // 20 | click | css=#difficulte > option:nth-child(4) | 
    await driver.findElement(By.css("#difficulte > option:nth-child(4)")).click()
    // 21 | click | id=plannification | 
    await driver.findElement(By.id("plannification")).click()
    // 22 | select | id=plannification | label=Sprint 1
    {
      const dropdown = await driver.findElement(By.id("plannification"))
      await dropdown.findElement(By.xpath("//option[. = 'Sprint 1']")).click()
    }
    // 23 | click | css=#plannification > option:nth-child(2) | 
    await driver.findElement(By.css("#plannification > option:nth-child(2)")).click()
    // 24 | click | css=.btn-success | 
    await driver.findElement(By.css(".btn-success")).click()
  })
})
