// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('creationproj', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('creationproj', async function() {
    await driver.get("http://localhost:3000/projectList")
    await driver.manage().window().setRect(995, 696)
    await driver.findElement(By.css(".btn-sm")).click()
    await driver.findElement(By.id("projectName")).click()
    await driver.findElement(By.id("projectName")).sendKeys("Nom du projet")
    await driver.findElement(By.id("projectDesc")).click()
    await driver.findElement(By.id("sprintDelay")).sendKeys("3")
    await driver.findElement(By.id("sprintDelay")).click()
    await driver.findElement(By.id("sprintDelay")).sendKeys("4")
    await driver.findElement(By.id("sprintDelay")).click()
    {
      const element = await driver.findElement(By.id("sprintDelay"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("projectDesc")).sendKeys("Description incroyable")
    await driver.findElement(By.id("dateEnd")).click()
    await driver.findElement(By.id("dateEnd")).sendKeys("2021-01-06")
    await driver.findElement(By.css(".btn-danger")).click()
  })
})
