name: TestE2E/Inte on push
on:
  push:
    branches: 
      - Thim

jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          working-directory: src
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          working-directory: src
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: src
          project: ./tests/cypress
          start : npm run app:test
          
